apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-card-rs
  labels:
    app: card
spec:
  selector:
    matchLabels:
      app: card
  template:
    metadata:
      labels:
        app: card
    spec:
      containers:
        - name: server-card-rs
          image: gmae199boy/server-card:latest
          ports:
            - containerPort: 3000
